### ISSUE TITLE
Broken scsi_target.lio when you add an ACL to qla2xxx.

### ISSUE THREAD

**Issue by jridore** [Datera/targetcli#15]
I added a target then added an ACL. I tried to saveconfig but it failed with this:
Created Node ACL for 21:01:00:1b:32:a2:7b:20
/qla2xxx/57:c...40:91:15/acls> saveconfig
Save configuration? [Y/n]: y
Performing backup of startup configuration: /var/target/backup-2015-10-05_14:51:40.lio
Saving new startup configuration
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 990, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 820, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 934, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 909, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/targetcli/ui_node.py", line 104, in execute_command
    pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell/node.py", line 1417, in execute_command
    result = method(*pparams, **kparams)
  File "/usr/lib/python2.7/site-packages/targetcli/ui_node.py", line 123, in ui_command_saveconfig
    CliConfig.save_running_config()
  File "/usr/lib/python2.7/site-packages/targetcli/cli_config.py", line 65, in save_running_config
    config.load_live()
  File "/usr/lib/python2.7/site-packages/rtslib/config.py", line 563, in load_live
    parse_tree = self._parser.parse_string(live)
  File "/usr/lib/python2.7/site-packages/rtslib/config_parser.py", line 148, in parse_string
    return self._parser.parseString(string, parseAll=True).asList()
  File "/usr/lib/python2.7/site-packages/pyparsing.py", line 1034, in parseString
    raise exc
ParseException: Expected end of text (at char 819), (line:30, col:1)

I stepped through this exception with pdb and noticed that the "json" is broken. When adding an acl the parent target's object is missing the closing brace after "enable 1".
fabric qla2xxx target 57:cc:95:a0:00:40:91:15 {
    attribute cache_dynamic_acls 1
    attribute demo_mode_write_protect 1
    attribute generate_node_acls 1
    attribute prod_mode_write_protect 0
    acl 21:01:00:1b:32:a2:7b:19 {
    }
    enable 1

**Comment by lynchs61** [comment]
Any updates to this? I'm getting the same error now on Ubuntu Server 16.04.1.
