### ISSUE TITLE
ParseException: Expected end of text (at char 0), (line:1, col:1)

### ISSUE THREAD

**Issue by zphj1987** [Datera/targetcli#21]
``` bash
/backstores/fileio> create name=zp file_or_dev=/dev/rbd0
/backstores/fileio> saveconfig 
Save configuration? [Y/n]: y
Performing backup of startup configuration: /var/target/backup-2016-01-28_17:43:48.lio
Saving new startup configuration
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/configshell/shell.py", line 990, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.6/site-packages/configshell/shell.py", line 813, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.6/site-packages/configshell/shell.py", line 934, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.6/site-packages/configshell/shell.py", line 909, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.6/site-packages/targetcli/ui_node.py", line 104, in execute_command
    pparams, kparams)
  File "/usr/lib/python2.6/site-packages/configshell/node.py", line 1405, in execute_command
    result = method(*pparams, **kparams)
  File "/usr/lib/python2.6/site-packages/targetcli/ui_node.py", line 123, in ui_command_saveconfig
    CliConfig.save_running_config()
  File "/usr/lib/python2.6/site-packages/targetcli/cli_config.py", line 65, in save_running_config
    config.load_live()
  File "/usr/lib/python2.6/site-packages/rtslib/config.py", line 563, in load_live
    parse_tree = self._parser.parse_string(live)
  File "/usr/lib/python2.6/site-packages/rtslib/config_parser.py", line 148, in parse_string
    return self._parser.parseString(string, parseAll=True).asList()
  File "/usr/lib/python2.6/site-packages/pyparsing.py", line 1032, in parseString
    raise exc
ParseException: Expected end of text (at char 0), (line:1, col:1)
```

i use a ceph rbd as a fileio  and it went wrong, i use the 
Using rtslib version 3.0.pre4.9~g6fd0bbf
Using targetcli version 3.0.pre4.5~ga125182

localdisk it will be well

some one help? thank you

**Comment by worldowner** [comment]
Similar issue here:

Saving new startup configuration
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 990, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 820, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 934, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 909, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/targetcli/ui_node.py", line 104, in execute_command
    pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/configshell/node.py", line 1416, in execute_command
    result = method(_pparams, *_kparams)
  File "/usr/lib/python2.7/dist-packages/targetcli/ui_node.py", line 123, in ui_command_saveconfig
    CliConfig.save_running_config()
  File "/usr/lib/python2.7/dist-packages/targetcli/cli_config.py", line 65, in save_running_config
    config.load_live()
  File "/usr/lib/python2.7/dist-packages/rtslib/config.py", line 561, in load_live
    parse_tree = self._parser.parse_string(live)
  File "/usr/lib/python2.7/dist-packages/rtslib/config_parser.py", line 148, in parse_string
    return self._parser.parseString(string, parseAll=True).asList()
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 1125, in parseString
    raise exc
ParseException: Expected end of text (at char 0), (line:1, col:1)

**Comment by frankf-cgn** [comment]
Same here. Error occured when savong after removeing luns and iblocks. Saving failed with the very same error message. After deleting the Node-ACLs, too, the error on saving was gone.

**Comment by albertor24** [comment]
For whoever is reading this, there is a "FIXME" on rtslib/config_parser.py. On line 81, that says empty blocks do not work as expected.

        # FIXME This does not work as intended when used
        # tok_empty_block = pp.Suppress('{' + pp.ZeroOrMore(tok_delim) + '}')

**Comment by zphj1987** [comment]
close
