### ISSUE TITLE
make rpm throws a syntax error

### ISSUE THREAD

**Issue by ankitsharda** [Datera/targetcli#23]
Hi ,

I've cloned the repository and am doing a "make rpm" as instructed in the readme

I get a syntax error as follows - 

Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    import targetcli
  File "/root/targetcli/build/rpm/BUILD/targetcli-3.0.pre4.5~ga125182/targetcli/**init**.py", line 18, in <module>
    from ui_root import UIRoot
  File "/root/targetcli/build/rpm/BUILD/targetcli-3.0.pre4.5~ga125182/targetcli/ui_root.py", line 21, in <module>
    from rtslib import RTSRoot, Config
  File "/usr/lib/python2.6/site-packages/rtslib/**init**.py", line 24, in <module>
    from .root import RTSRoot
  File "/usr/lib/python2.6/site-packages/rtslib/root.py", line 27, in <module>
    from .fabric import FabricModule
  File "/usr/lib/python2.6/site-packages/rtslib/fabric.py", line 121
    version_attributes = {"lio_version", "version"}**
                                       ^
SyntaxError: invalid syntax
error: Bad exit status from /var/tmp/rpm-tmp.RGCW43 (%build)

I'm on CentOS release 6.6 (Final), Python 2.6.6

Any help would be appreciated

**Comment by frankf-cgn** [comment]
Ran into the same. You have to build configshell and rtlib manually, too. My build on CentOS 7 was something like this:

`python-configshell:`

```
yum remove python-rtslib python-configshell -y
yum install epydoc
git clone https://github.com/Datera/configshell.git
cd configshell/
make rpm
rpm -ivh dist/python-configshell-1.6.1~g020d540-1.el7.centos.noarch.rpm
```

`python-rtslib:`

```
yum install python-netifaces python-ipaddr
git clone https://github.com/Datera/rtslib.git
cd rtslib/
make rpm
rpm -ivh dist/python-rtslib-3.0.pre4.9~g6fd0bbf-1.el7.centos.noarch.rpm 
```

`targetcli:`

```
yum install python-prettytable
git clone https://github.com/Datera/targetcli.git
cd targetcli/
make rpm
rpm -ivh dist/targetcli-3.0.pre4.5~ga125182-1.el7.centos.noarch.rpm 
```

#### CentOS 7 kernel

I have used the kernelversion 3.18.30-20.el7.x86_64 from http://mirror.centos.org/centos/7/virt/x86_64/xen/
This is the CentOS/virt repository

**Comment by petercdickinson** [comment]
Thanks. I ran into the same problem building on Fedora 24.
