### ISSUE TITLE
Error on centos 7 

### ISSUE THREAD

**Issue by mortezagh** [Datera/targetcli#25]
Hi 
what is this error for >?

[root@NAS-HP targetcli]# make rpm
Exporting the repository files...
Cleaning up the target tree...
Fixing version string...
Generating rpm specfile from template...
Generating rpm changelog...
Generating debian changelog...
Generated release tarball:
    dist/targetcli-3.0.pre4.5~ga125182.tar.gz
Building rpm packages...
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.Y1fx1o
+ umask 022
+ cd /home/targetcli/build/rpm/BUILD
+ cd /home/targetcli/build/rpm/BUILD
+ rm -rf targetcli-3.0.pre4.5~ga125182
+ /usr/bin/gzip -dc /home/targetcli/dist/targetcli-3.0.pre4.5~ga125182.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd targetcli-3.0.pre4.5~ga125182
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.LJ44F7
+ umask 022
+ cd /home/targetcli/build/rpm/BUILD
+ cd targetcli-3.0.pre4.5~ga125182
+ /usr/bin/python setup.py build
/home/targetcli/build/rpm/BUILD/targetcli-3.0.pre4.5~ga125182/targetcli/ui_root.py:21: UserWarning: 'rtslib' package name for rtslib-fb is deprecated, please instead import 'rtslib_fb'
  from rtslib import RTSRoot, Config
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    import targetcli
  File "/home/targetcli/build/rpm/BUILD/targetcli-3.0.pre4.5~ga125182/targetcli/__init__.py", line 18, in <module>
    from ui_root import UIRoot
  File "/home/targetcli/build/rpm/BUILD/targetcli-3.0.pre4.5~ga125182/targetcli/ui_root.py", line 21, in <module>
    from rtslib import RTSRoot, Config
ImportError: cannot import name Config
error: Bad exit status from /var/tmp/rpm-tmp.LJ44F7 (%build)

**Comment by agrover** [comment]
You need to also use datera rtslib and configshell, not what ships in centos.
