### ISSUE TITLE
cannot save config

### ISSUE THREAD

**Issue by rickysarraf** [Datera/targetcli#7]
14:27:16 rrs@learner:/var/tmp/Debian-Build/Result$ sudo targetcli
targetcli GIT_VERSION (rtslib GIT_VERSION)
Copyright (c) 2011-2014 by Datera, Inc.
All rights reserved.

/> ls
o- / ................................................................................................... [...]
  o- backstores ........................................................................................ [...]
  | o- fileio ............................................................................. [0 Storage Object]
  | o- iblock ............................................................................. [0 Storage Object]
  | o- pscsi .............................................................................. [0 Storage Object]
  | o- rd_mcp ............................................................................. [0 Storage Object]
  o- ib_srpt ..................................................................................... [0 Targets]
  o- iscsi ....................................................................................... [0 Targets]
  o- loopback .................................................................................... [0 Targets]
  o- qla2xxx ..................................................................................... [0 Targets]
  o- tcm_fc ...................................................................................... [0 Targets]
  o- vhost ....................................................................................... [0 Targets]
/> /backstores/fileio 
/backstores/fileio> ls
o- fileio ................................................................................. [0 Storage Object]
/backstores/fileio> create test /tmp/test.img 10m
Using buffered mode.
Created fileio test.
/backstores/fileio> cd /
/> saveconfig
Save configuration? [Y/n]: y
Saving new startup configuration
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 990, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 820, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 934, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 909, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/targetcli/ui_node.py", line 104, in execute_command
    pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/configshell/node.py", line 1416, in execute_command
    result = method(*pparams, **kparams)
  File "/usr/lib/python2.7/dist-packages/targetcli/ui_node.py", line 123, in ui_command_saveconfig
    CliConfig.save_running_config()
  File "/usr/lib/python2.7/dist-packages/targetcli/cli_config.py", line 65, in save_running_config
    config.load_live()
  File "/usr/lib/python2.7/dist-packages/rtslib/config.py", line 565, in load_live
    source=source, allow_new_attrs=True)
  File "/usr/lib/python2.7/dist-packages/rtslib/config.py", line 190, in _load_parse_tree
    token = self.validate_obj(token, cur)
  File "/usr/lib/python2.7/dist-packages/rtslib/config.py", line 385, in validate_obj
    raise ConfigError("Unknown object type: %s" % obj_type)
ConfigError: Unknown object type: storage
/>

**Comment by tramjoe** [comment]
Closing as related to a bad build.
