### ISSUE TITLE
Create exeption with "longobject.c:998: bad argument to internal function"

### ISSUE THREAD

**Issue by Nefelim4ag** [Datera/targetcli#8]
Ubuntu 15.04 targetcli from ubuntu repos
Same error for any block device

/backstores/iblock> create dev=/dev/rbd/rbd/storage name=storage
Generating a wwn serial.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 990, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 820, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 934, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 909, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/targetcli/ui_node.py", line 103, in execute_command
    pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/configshell/node.py", line 1416, in execute_command
    result = method(*pparams, **kparams)
  File "/usr/lib/python2.7/dist-packages/targetcli/ui_backstore.py", line 394, in ui_command_create
    raise exception
SystemError: ../Objects/longobject.c:998: bad argument to internal function

**Comment by tramjoe** [comment]
Need to install ubuntu and reproduce, bust most likely a python ubuntu-related breakage. Will investigate anyway in case it is something from our side, but seems related to a known bug in python 2.7.9:

https://bugs.python.org/issue23842
https://hg.python.org/cpython/file/default/Objects/longobject.c#l998

What is the version of python that you use, and can you retest with an older or more recent one?
